#!/bin/bash

make > /dev/null

cat $1 2>/dev/null || { echo "\"$1\" not found"; exit; }
out=$(echo $1 | cut -d"." -f1)
echo -n "Press Enter to Continue" && read

java Parser $1 | tee ../5.Intermediate_Code_Optimization/$out
